---
- name: 'RedHat | Configure the repository and install the GitLab Runner package'
  become: true
  block:
    - name: 'RedHat | Ensure dependencies are installed'
      ansible.builtin.package:
        name: 'yum-utils'
        state: 'present'

    - name: 'RedHat | Add the GitLab Runner repository'
      ansible.builtin.template:
        src: 'gitlab-runner.repo.j2'
        dest: '/etc/yum.repos.d/runner_gitlab-runner.repo'
        owner: 'root'
        group: 'root'
        mode: 0644

    - name: 'RedHat | Install the GitLab Runner package'
      ansible.builtin.yum:
        name: "gitlab-runner{{ ('-' + gitlab_runner_package_version) if (gitlab_runner_package_version | length) else '' }}"
        allow_downgrade: true
        update_cache: true
        state: "{{ 'present' if (gitlab_runner_package_version | length) else 'latest' }}"
      when: not ansible_check_mode
