---
- name: 'Configure APT repository and install Gitlab Runner package'
  become: true
  block:
    - name: 'Ensure dependencies are installed'
      ansible.builtin.apt:
        name:
          - 'apt-transport-https'
          - 'gnupg'
        update_cache: true
        state: 'present'
      when: not ansible_check_mode

    - name: 'Add Gitlab Runner APT key'
      ansible.builtin.apt_key:
        url: '{{ gitlab_runner_repository_gpgkey_url }}'
        keyring: '{{ _gitlab_runner_local_gpgkey_path }}'
        state: 'present'

    - name: 'Add Gitlab Runner APT repository'
      ansible.builtin.template:
        src: 'gitlab-runner.list.j2'
        dest: '/etc/apt/sources.list.d/gitlab-runner.list'
        owner: 'root'
        group: 'root'
        mode: 0644

    - name: 'Install Gitlab Runner package'
      ansible.builtin.apt:
        name: "gitlab-runner{{ ('=' + gitlab_runner_package_version) if (gitlab_runner_package_version | length) else '' }}"
        allow_downgrade: true
        update_cache: true
        state: "{{ 'present' if (gitlab_runner_package_version | length) else 'latest' }}"
      when: not ansible_check_mode
