---
- name: 'Configure YUM/DNF repository and install Gitlab Runner package'
  become: true
  block:
    - name: 'Ensure dependencies are installed'
      ansible.builtin.package:
        name: yum-utils
        state: present

    - name: 'Add Gitlab Runner DNF/YUM repository'
      ansible.builtin.template:
        src: 'gitlab-runner.repo.j2'
        dest: '/etc/yum.repos.d/gitlab-runner.repo'
        owner: 'root'
        group: 'root'
        mode: 0644

    - name: 'Install Gitlab Runner package'
      ansible.builtin.yum:
        name: "gitlab-runner{{ ('-' + gitlab_runner_version) if (gitlab_runner_version | length) else '' }}"
        allow_downgrade: true
        update_cache: true
        state: "{{ 'present' if (gitlab_runner_version | length) else 'latest' }}"
