---
- name: 'Verify'
  hosts: all
  gather_facts: false
  tasks:
    - name: 'Gathering Service Facts'
      ansible.builtin.service_facts:

    - name: 'Assert that gitlab-runner service is enabled and running'
      ansible.builtin.assert:
        that:
          - ansible_facts.services['gitlab-runner.service'].state == 'running' or
            ansible_facts.services['gitlab-runner.service'].state == 'active'
          - ansible_facts.services['gitlab-runner.service'].status == 'enabled' or
            ansible_facts.services['gitlab-runner.service'].status == 'enabled'

    - name: 'Check current Gitlab Runner version'
      ansible.builtin.command:
        cmd: '/usr/bin/gitlab-runner --version'
      changed_when: false
      register: __gitlab_runner_version_check

    - name: 'Version output'
      ansible.builtin.debug:
        var: __gitlab_runner_version_check.stdout_lines[0].split()[1]
