---
- name: 'Linux | Prepare for installing GitLab Runner'
  become: true
  block:
    - name: Linux | Create a GitLab Runner group'
      ansible.builtin.group:
        name: 'gitlab-runner'
        system: true

    - name: 'Linux | Create a GitLab Runner user'
      ansible.builtin.user:
        name: 'gitlab-runner'
        comment: 'GitLab Runner'
        system: true
        createhome: true
        shell: '/bin/bash'

- name: 'Linux | Check if GitLab Runner is installed'
  ansible.builtin.stat:
    path: '{{ gitlab_runner_binary_install_path }}/gitlab-runner'
  register: __gitlab_runner_binary_is_installed

- name: 'Linux | Check the current GitLab Runner version'
  ansible.builtin.command:
    cmd: '{{ gitlab_runner_binary_install_path }}/gitlab-runner --version'
  failed_when: false
  changed_when: false
  register: __gitlab_runner_binary_version_check

- name: 'Linux | Download and install GitLab Runner'
  when:
    - not __gitlab_runner_binary_is_installed.stat.exists or
      (__gitlab_runner_binary_version_check.stdout_lines | length and
      gitlab_runner_binary_version not in __gitlab_runner_binary_version_check.stdout_lines[0].split()[1])
  block:
    - name: 'Linux | Download the GitLab Runner binary to a local folder'
      become: false
      ansible.builtin.get_url:
        url: '{{ gitlab_runner_binary_download_url }}/{{ gitlab_runner_binary_name }}'
        dest: '{{ gitlab_runner_binary_download_path }}/{{ gitlab_runner_binary_name }}-{{ gitlab_runner_binary_version }}'
        mode: 0644
      register: __gitlab_runner_binary_download_result
      until: __gitlab_runner_binary_download_result is succeeded
      retries: 3
      delay: 5
      delegate_to: localhost
      check_mode: false

    - name: 'Linux | Ensure the GitLab Runner service is stopped before version update'
      become: true
      ansible.builtin.systemd:
        name: 'gitlab-runner'
        state: 'stopped'
      when:
        - __gitlab_runner_binary_is_installed.stat.exists and
          gitlab_runner_binary_version not in __gitlab_runner_binary_version_check.stdout_lines[0].split()[1]

    - name: 'Linux | Copy the GitLab Runner binary to a target host'
      become: true
      ansible.builtin.copy:
        src: '{{ gitlab_runner_binary_download_path }}/{{ gitlab_runner_binary_name }}-{{ gitlab_runner_binary_version }}'
        dest: '{{ gitlab_runner_binary_install_path }}/gitlab-runner'
        owner: 'root'
        mode: 0755
      when: not ansible_check_mode

    - name: 'Linux | Ensure the GitLab Runner service is installed'
      become: true
      ansible.builtin.command:
        cmd: '"{{ gitlab_runner_binary_install_path }}/gitlab-runner" install --user gitlab-runner --working-directory /home/gitlab-runner'
        creates: '/etc/gitlab-runner'
      when: not __gitlab_runner_binary_is_installed.stat.exists

- name: 'Linux | Ensure the GitLab Runner service is running and enabled at boot'
  become: true
  ansible.builtin.systemd:
    name: 'gitlab-runner'
    enabled: true
    state: 'started'
